name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
      - "releases/v*"
  pull_request:
    branches:
      - "releases/v*"
      - development

env:
  JDK_VERSION: 21
  GRADLE_VERSION: 8.11

jobs:
  tests:
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  # Format PR
  format_check:
    name: Checks Source Code Formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ env.JDK_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - uses: Ortus-Solutions/commandbox-action@v1.0.3
        with:
          cmd: run-script format:check

      - name: Verify Code Formatting
        run: gradle spotlessCheck
